CREATE USER replicator WITH SUPERUSER PASSWORD '112233';
CREATE USER replica_user WITH PASSWORD '112233';
GRANT CREATE REPLICA SLOT TO replicator;
ALTER USER replica_user WITH REPLICATION;

CREATE PUBLICATION my_publication FOR TABLE test;
